/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ILuciaPoolDeployer } from "../ILuciaPoolDeployer";

export class ILuciaPoolDeployer__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILuciaPoolDeployer {
    return new Contract(address, _abi, signerOrProvider) as ILuciaPoolDeployer;
  }
}

const _abi = [
  {
    inputs: [],
    name: "parameters",
    outputs: [
      {
        internalType: "address",
        name: "factory",
        type: "address",
      },
      {
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        internalType: "address",
        name: "token1",
        type: "address",
      },
      {
        internalType: "uint24",
        name: "fee",
        type: "uint24",
      },
      {
        internalType: "int24",
        name: "tickSpacing",
        type: "int24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
